name: Alpha

on:
  push:
    tags:
      - 'alpha/*'


jobs:

  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Initialise build environment
      run: yarn install

    - name: Build release for linux64
      run: yarn gulp release --linux64

    - name: Move artifacts
      run: mv release/rotorflight-configurator* .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rotorflight-configurator-linux-alpha-${{ env.GIT_VER }}
        path: rotorflight-configurator*


  macos:

    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Initialise build environment
      run: yarn install

    - name: Build release for MacOS
      run: yarn gulp release --osx64

    - name: Move artifacts
      run: mv release/rotorflight-configurator* .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rotorflight-configurator-macos-alpha-${{ env.GIT_VER }}
        path: rotorflight-configurator*


  windows:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Set build variables
      run: |
        $GIT_VER = $env:GITHUB_REF -replace '.*/',''
        echo "GIT_VER=$GIT_VER" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Initialise build environment
      run: yarn install

    - name: Build release for windows
      run: yarn gulp release --win64

    - name: Move artifacts
      run: move release/rotorflight-configurator* .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rotorflight-configurator-windows-alpha-${{ env.GIT_VER }}
        path: rotorflight-configurator*

