name: Snapshot

on:
  push:
    tags:
      - 'snapshot/*'

jobs:

  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.1

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Initialise build environment
      run: yarn install

    - name: Build release for linux64
      run: yarn gulp release --linux64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-configurator-linux-snapshot-${{ env.GIT_VER }}
        path: release/rotorflight-configurator*


  macos:

    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.1

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Initialise build environment
      run: yarn install

    - name: Build release for MacOS
      run: yarn gulp release --osx64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-configurator-macos-snapshot-${{ env.GIT_VER }}
        path: release/rotorflight-configurator*


  windows:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.1

    - name: Set build variables
      run: |
        $GIT_VER = $env:GITHUB_REF -replace '.*/',''
        echo "GIT_VER=$GIT_VER" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Initialise build environment
      run: yarn install

    - name: Build release for windows
      run: yarn gulp release --win64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-configurator-windows-snapshot-${{ env.GIT_VER }}
        path: release/rotorflight-configurator*


  snapshot:

    runs-on: ubuntu-latest

    needs: [linux, windows, macos]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        echo "GIT_TAG=${GITHUB_REF##refs/tags/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Download Linux Artifacts
      uses: actions/download-artifact@v2
      with:
        name: rotorflight-configurator-linux-snapshot-${{ env.GIT_VER }}

    - name: Download MacOS Artifacts
      uses: actions/download-artifact@v2
      with:
        name: rotorflight-configurator-macos-snapshot-${{ env.GIT_VER }}

    - name: Download Windows Artifacts
      uses: actions/download-artifact@v2
      with:
        name: rotorflight-configurator-windows-snapshot-${{ env.GIT_VER }}

    - name: Create Snapshot
      run: |
        gh release create ${{ env.GIT_TAG }} --prerelease --notes-file "Snapshot.md" --title "Rotorflight Configurator Snapshot ${{ env.GIT_VER }}" rotorflight-configurator*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

